/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Lecturer service. Represents a row in the &quot;syllabus_manager_Lecturer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.unideb.inf.model.impl.LecturerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.unideb.inf.model.impl.LecturerImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see Lecturer
 * @see hu.unideb.inf.model.impl.LecturerImpl
 * @see hu.unideb.inf.model.impl.LecturerModelImpl
 * @generated
 */
@ProviderType
public interface LecturerModel extends BaseModel<Lecturer>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lecturer model instance should use the {@link Lecturer} interface instead.
	 */

	/**
	 * Returns the primary key of this lecturer.
	 *
	 * @return the primary key of this lecturer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lecturer.
	 *
	 * @param primaryKey the primary key of this lecturer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lecturer ID of this lecturer.
	 *
	 * @return the lecturer ID of this lecturer
	 */
	public long getLecturerId();

	/**
	 * Sets the lecturer ID of this lecturer.
	 *
	 * @param lecturerId the lecturer ID of this lecturer
	 */
	public void setLecturerId(long lecturerId);

	/**
	 * Returns the group ID of this lecturer.
	 *
	 * @return the group ID of this lecturer
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this lecturer.
	 *
	 * @param groupId the group ID of this lecturer
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this lecturer.
	 *
	 * @return the company ID of this lecturer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lecturer.
	 *
	 * @param companyId the company ID of this lecturer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this lecturer.
	 *
	 * @return the user ID of this lecturer
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this lecturer.
	 *
	 * @param userId the user ID of this lecturer
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lecturer.
	 *
	 * @return the user uuid of this lecturer
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lecturer.
	 *
	 * @param userUuid the user uuid of this lecturer
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this lecturer.
	 *
	 * @return the user name of this lecturer
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this lecturer.
	 *
	 * @param userName the user name of this lecturer
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this lecturer.
	 *
	 * @return the create date of this lecturer
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this lecturer.
	 *
	 * @param createDate the create date of this lecturer
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this lecturer.
	 *
	 * @return the modified date of this lecturer
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this lecturer.
	 *
	 * @param modifiedDate the modified date of this lecturer
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the lecturer name of this lecturer.
	 *
	 * @return the lecturer name of this lecturer
	 */
	@AutoEscape
	public String getLecturerName();

	/**
	 * Sets the lecturer name of this lecturer.
	 *
	 * @param lecturerName the lecturer name of this lecturer
	 */
	public void setLecturerName(String lecturerName);

	/**
	 * Returns the lecturer user ID of this lecturer.
	 *
	 * @return the lecturer user ID of this lecturer
	 */
	public long getLecturerUserId();

	/**
	 * Sets the lecturer user ID of this lecturer.
	 *
	 * @param lecturerUserId the lecturer user ID of this lecturer
	 */
	public void setLecturerUserId(long lecturerUserId);

	/**
	 * Returns the lecturer user uuid of this lecturer.
	 *
	 * @return the lecturer user uuid of this lecturer
	 */
	public String getLecturerUserUuid();

	/**
	 * Sets the lecturer user uuid of this lecturer.
	 *
	 * @param lecturerUserUuid the lecturer user uuid of this lecturer
	 */
	public void setLecturerUserUuid(String lecturerUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(hu.unideb.inf.model.Lecturer lecturer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.unideb.inf.model.Lecturer> toCacheModel();

	@Override
	public hu.unideb.inf.model.Lecturer toEscapedModel();

	@Override
	public hu.unideb.inf.model.Lecturer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}