/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Syllabus service. Represents a row in the &quot;syllabus_manager_Syllabus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.unideb.inf.model.impl.SyllabusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.unideb.inf.model.impl.SyllabusImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see Syllabus
 * @see hu.unideb.inf.model.impl.SyllabusImpl
 * @see hu.unideb.inf.model.impl.SyllabusModelImpl
 * @generated
 */
@ProviderType
public interface SyllabusModel extends BaseModel<Syllabus>, GroupedModel,
	ShardedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a syllabus model instance should use the {@link Syllabus} interface instead.
	 */

	/**
	 * Returns the primary key of this syllabus.
	 *
	 * @return the primary key of this syllabus
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this syllabus.
	 *
	 * @param primaryKey the primary key of this syllabus
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the syllabus ID of this syllabus.
	 *
	 * @return the syllabus ID of this syllabus
	 */
	public long getSyllabusId();

	/**
	 * Sets the syllabus ID of this syllabus.
	 *
	 * @param syllabusId the syllabus ID of this syllabus
	 */
	public void setSyllabusId(long syllabusId);

	/**
	 * Returns the group ID of this syllabus.
	 *
	 * @return the group ID of this syllabus
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this syllabus.
	 *
	 * @param groupId the group ID of this syllabus
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this syllabus.
	 *
	 * @return the company ID of this syllabus
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this syllabus.
	 *
	 * @param companyId the company ID of this syllabus
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this syllabus.
	 *
	 * @return the user ID of this syllabus
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this syllabus.
	 *
	 * @param userId the user ID of this syllabus
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this syllabus.
	 *
	 * @return the user uuid of this syllabus
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this syllabus.
	 *
	 * @param userUuid the user uuid of this syllabus
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this syllabus.
	 *
	 * @return the user name of this syllabus
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this syllabus.
	 *
	 * @param userName the user name of this syllabus
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this syllabus.
	 *
	 * @return the create date of this syllabus
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this syllabus.
	 *
	 * @param createDate the create date of this syllabus
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this syllabus.
	 *
	 * @return the modified date of this syllabus
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this syllabus.
	 *
	 * @param modifiedDate the modified date of this syllabus
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the timetable course ID of this syllabus.
	 *
	 * @return the timetable course ID of this syllabus
	 */
	public long getTimetableCourseId();

	/**
	 * Sets the timetable course ID of this syllabus.
	 *
	 * @param timetableCourseId the timetable course ID of this syllabus
	 */
	public void setTimetableCourseId(long timetableCourseId);

	/**
	 * Returns the competence of this syllabus.
	 *
	 * @return the competence of this syllabus
	 */
	@AutoEscape
	public String getCompetence();

	/**
	 * Sets the competence of this syllabus.
	 *
	 * @param competence the competence of this syllabus
	 */
	public void setCompetence(String competence);

	/**
	 * Returns the ethical standards of this syllabus.
	 *
	 * @return the ethical standards of this syllabus
	 */
	@AutoEscape
	public String getEthicalStandards();

	/**
	 * Sets the ethical standards of this syllabus.
	 *
	 * @param ethicalStandards the ethical standards of this syllabus
	 */
	public void setEthicalStandards(String ethicalStandards);

	/**
	 * Returns the topics of this syllabus.
	 *
	 * @return the topics of this syllabus
	 */
	@AutoEscape
	public String getTopics();

	/**
	 * Sets the topics of this syllabus.
	 *
	 * @param topics the topics of this syllabus
	 */
	public void setTopics(String topics);

	/**
	 * Returns the educational materials of this syllabus.
	 *
	 * @return the educational materials of this syllabus
	 */
	@AutoEscape
	public String getEducationalMaterials();

	/**
	 * Sets the educational materials of this syllabus.
	 *
	 * @param educationalMaterials the educational materials of this syllabus
	 */
	public void setEducationalMaterials(String educationalMaterials);

	/**
	 * Returns the recommended literature of this syllabus.
	 *
	 * @return the recommended literature of this syllabus
	 */
	@AutoEscape
	public String getRecommendedLiterature();

	/**
	 * Sets the recommended literature of this syllabus.
	 *
	 * @param recommendedLiterature the recommended literature of this syllabus
	 */
	public void setRecommendedLiterature(String recommendedLiterature);

	/**
	 * Returns the weekly tasks of this syllabus.
	 *
	 * @return the weekly tasks of this syllabus
	 */
	@AutoEscape
	public String getWeeklyTasks();

	/**
	 * Sets the weekly tasks of this syllabus.
	 *
	 * @param weeklyTasks the weekly tasks of this syllabus
	 */
	public void setWeeklyTasks(String weeklyTasks);

	/**
	 * Returns the status of this syllabus.
	 *
	 * @return the status of this syllabus
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this syllabus.
	 *
	 * @param status the status of this syllabus
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this syllabus.
	 *
	 * @return the status by user ID of this syllabus
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this syllabus.
	 *
	 * @param statusByUserId the status by user ID of this syllabus
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this syllabus.
	 *
	 * @return the status by user uuid of this syllabus
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this syllabus.
	 *
	 * @param statusByUserUuid the status by user uuid of this syllabus
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this syllabus.
	 *
	 * @return the status by user name of this syllabus
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this syllabus.
	 *
	 * @param statusByUserName the status by user name of this syllabus
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this syllabus.
	 *
	 * @return the status date of this syllabus
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this syllabus.
	 *
	 * @param statusDate the status date of this syllabus
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this syllabus is approved.
	 *
	 * @return <code>true</code> if this syllabus is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this syllabus is denied.
	 *
	 * @return <code>true</code> if this syllabus is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this syllabus is a draft.
	 *
	 * @return <code>true</code> if this syllabus is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this syllabus is expired.
	 *
	 * @return <code>true</code> if this syllabus is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this syllabus is inactive.
	 *
	 * @return <code>true</code> if this syllabus is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this syllabus is incomplete.
	 *
	 * @return <code>true</code> if this syllabus is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this syllabus is pending.
	 *
	 * @return <code>true</code> if this syllabus is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this syllabus is scheduled.
	 *
	 * @return <code>true</code> if this syllabus is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(hu.unideb.inf.model.Syllabus syllabus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.unideb.inf.model.Syllabus> toCacheModel();

	@Override
	public hu.unideb.inf.model.Syllabus toEscapedModel();

	@Override
	public hu.unideb.inf.model.Syllabus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}