/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Curriculum service. Represents a row in the &quot;unideb_syllabus_manager_Curriculum&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.unideb.inf.model.impl.CurriculumModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.unideb.inf.model.impl.CurriculumImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see Curriculum
 * @see hu.unideb.inf.model.impl.CurriculumImpl
 * @see hu.unideb.inf.model.impl.CurriculumModelImpl
 * @generated
 */
public interface CurriculumModel extends BaseModel<Curriculum>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a curriculum model instance should use the {@link Curriculum} interface instead.
	 */

	/**
	 * Returns the primary key of this curriculum.
	 *
	 * @return the primary key of this curriculum
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this curriculum.
	 *
	 * @param primaryKey the primary key of this curriculum
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the curriculum ID of this curriculum.
	 *
	 * @return the curriculum ID of this curriculum
	 */
	public long getCurriculumId();

	/**
	 * Sets the curriculum ID of this curriculum.
	 *
	 * @param curriculumId the curriculum ID of this curriculum
	 */
	public void setCurriculumId(long curriculumId);

	/**
	 * Returns the group ID of this curriculum.
	 *
	 * @return the group ID of this curriculum
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this curriculum.
	 *
	 * @param groupId the group ID of this curriculum
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this curriculum.
	 *
	 * @return the company ID of this curriculum
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this curriculum.
	 *
	 * @param companyId the company ID of this curriculum
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this curriculum.
	 *
	 * @return the user ID of this curriculum
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this curriculum.
	 *
	 * @param userId the user ID of this curriculum
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this curriculum.
	 *
	 * @return the user uuid of this curriculum
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this curriculum.
	 *
	 * @param userUuid the user uuid of this curriculum
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this curriculum.
	 *
	 * @return the user name of this curriculum
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this curriculum.
	 *
	 * @param userName the user name of this curriculum
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this curriculum.
	 *
	 * @return the create date of this curriculum
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this curriculum.
	 *
	 * @param createDate the create date of this curriculum
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this curriculum.
	 *
	 * @return the modified date of this curriculum
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this curriculum.
	 *
	 * @param modifiedDate the modified date of this curriculum
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the curriculum code of this curriculum.
	 *
	 * @return the curriculum code of this curriculum
	 */
	@AutoEscape
	public String getCurriculumCode();

	/**
	 * Sets the curriculum code of this curriculum.
	 *
	 * @param curriculumCode the curriculum code of this curriculum
	 */
	public void setCurriculumCode(String curriculumCode);

	/**
	 * Returns the curriculum name of this curriculum.
	 *
	 * @return the curriculum name of this curriculum
	 */
	@AutoEscape
	public String getCurriculumName();

	/**
	 * Sets the curriculum name of this curriculum.
	 *
	 * @param curriculumName the curriculum name of this curriculum
	 */
	public void setCurriculumName(String curriculumName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(hu.unideb.inf.model.Curriculum curriculum);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.unideb.inf.model.Curriculum> toCacheModel();

	@Override
	public hu.unideb.inf.model.Curriculum toEscapedModel();

	@Override
	public hu.unideb.inf.model.Curriculum toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}