/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Lecturer service. Represents a row in the &quot;unideb_syllabus_manager_Lecturer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.unideb.inf.model.impl.LecturerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.unideb.inf.model.impl.LecturerImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see Lecturer
 * @see hu.unideb.inf.model.impl.LecturerImpl
 * @see hu.unideb.inf.model.impl.LecturerModelImpl
 * @generated
 */
public interface LecturerModel extends BaseModel<Lecturer> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lecturer model instance should use the {@link Lecturer} interface instead.
	 */

	/**
	 * Returns the primary key of this lecturer.
	 *
	 * @return the primary key of this lecturer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lecturer.
	 *
	 * @param primaryKey the primary key of this lecturer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lecturer ID of this lecturer.
	 *
	 * @return the lecturer ID of this lecturer
	 */
	public long getLecturerId();

	/**
	 * Sets the lecturer ID of this lecturer.
	 *
	 * @param lecturerId the lecturer ID of this lecturer
	 */
	public void setLecturerId(long lecturerId);

	/**
	 * Returns the lecturer name of this lecturer.
	 *
	 * @return the lecturer name of this lecturer
	 */
	@AutoEscape
	public String getLecturerName();

	/**
	 * Sets the lecturer name of this lecturer.
	 *
	 * @param lecturerName the lecturer name of this lecturer
	 */
	public void setLecturerName(String lecturerName);

	/**
	 * Returns the user ID of this lecturer.
	 *
	 * @return the user ID of this lecturer
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lecturer.
	 *
	 * @param userId the user ID of this lecturer
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lecturer.
	 *
	 * @return the user uuid of this lecturer
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this lecturer.
	 *
	 * @param userUuid the user uuid of this lecturer
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(hu.unideb.inf.model.Lecturer lecturer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.unideb.inf.model.Lecturer> toCacheModel();

	@Override
	public hu.unideb.inf.model.Lecturer toEscapedModel();

	@Override
	public hu.unideb.inf.model.Lecturer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}