/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Semester service. Represents a row in the &quot;unideb_syllabus_manager_Semester&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.unideb.inf.model.impl.SemesterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.unideb.inf.model.impl.SemesterImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see Semester
 * @see hu.unideb.inf.model.impl.SemesterImpl
 * @see hu.unideb.inf.model.impl.SemesterModelImpl
 * @generated
 */
public interface SemesterModel extends BaseModel<Semester>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a semester model instance should use the {@link Semester} interface instead.
	 */

	/**
	 * Returns the primary key of this semester.
	 *
	 * @return the primary key of this semester
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this semester.
	 *
	 * @param primaryKey the primary key of this semester
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the semester ID of this semester.
	 *
	 * @return the semester ID of this semester
	 */
	public long getSemesterId();

	/**
	 * Sets the semester ID of this semester.
	 *
	 * @param semesterId the semester ID of this semester
	 */
	public void setSemesterId(long semesterId);

	/**
	 * Returns the group ID of this semester.
	 *
	 * @return the group ID of this semester
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this semester.
	 *
	 * @param groupId the group ID of this semester
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this semester.
	 *
	 * @return the company ID of this semester
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this semester.
	 *
	 * @param companyId the company ID of this semester
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this semester.
	 *
	 * @return the user ID of this semester
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this semester.
	 *
	 * @param userId the user ID of this semester
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this semester.
	 *
	 * @return the user uuid of this semester
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this semester.
	 *
	 * @param userUuid the user uuid of this semester
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this semester.
	 *
	 * @return the user name of this semester
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this semester.
	 *
	 * @param userName the user name of this semester
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this semester.
	 *
	 * @return the create date of this semester
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this semester.
	 *
	 * @param createDate the create date of this semester
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this semester.
	 *
	 * @return the modified date of this semester
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this semester.
	 *
	 * @param modifiedDate the modified date of this semester
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the begin year of this semester.
	 *
	 * @return the begin year of this semester
	 */
	public int getBeginYear();

	/**
	 * Sets the begin year of this semester.
	 *
	 * @param beginYear the begin year of this semester
	 */
	public void setBeginYear(int beginYear);

	/**
	 * Returns the end year of this semester.
	 *
	 * @return the end year of this semester
	 */
	public int getEndYear();

	/**
	 * Sets the end year of this semester.
	 *
	 * @param endYear the end year of this semester
	 */
	public void setEndYear(int endYear);

	/**
	 * Returns the division of this semester.
	 *
	 * @return the division of this semester
	 */
	public int getDivision();

	/**
	 * Sets the division of this semester.
	 *
	 * @param division the division of this semester
	 */
	public void setDivision(int division);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(hu.unideb.inf.model.Semester semester);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.unideb.inf.model.Semester> toCacheModel();

	@Override
	public hu.unideb.inf.model.Semester toEscapedModel();

	@Override
	public hu.unideb.inf.model.Semester toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}