/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Subject service. Represents a row in the &quot;unideb_syllabus_manager_Subject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hu.unideb.inf.model.impl.SubjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hu.unideb.inf.model.impl.SubjectImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see Subject
 * @see hu.unideb.inf.model.impl.SubjectImpl
 * @see hu.unideb.inf.model.impl.SubjectModelImpl
 * @generated
 */
public interface SubjectModel extends BaseModel<Subject>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subject model instance should use the {@link Subject} interface instead.
	 */

	/**
	 * Returns the primary key of this subject.
	 *
	 * @return the primary key of this subject
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subject.
	 *
	 * @param primaryKey the primary key of this subject
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the subject ID of this subject.
	 *
	 * @return the subject ID of this subject
	 */
	public long getSubjectId();

	/**
	 * Sets the subject ID of this subject.
	 *
	 * @param subjectId the subject ID of this subject
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Returns the group ID of this subject.
	 *
	 * @return the group ID of this subject
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this subject.
	 *
	 * @param groupId the group ID of this subject
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this subject.
	 *
	 * @return the company ID of this subject
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this subject.
	 *
	 * @param companyId the company ID of this subject
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this subject.
	 *
	 * @return the user ID of this subject
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this subject.
	 *
	 * @param userId the user ID of this subject
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this subject.
	 *
	 * @return the user uuid of this subject
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this subject.
	 *
	 * @param userUuid the user uuid of this subject
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this subject.
	 *
	 * @return the user name of this subject
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this subject.
	 *
	 * @param userName the user name of this subject
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this subject.
	 *
	 * @return the create date of this subject
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this subject.
	 *
	 * @param createDate the create date of this subject
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this subject.
	 *
	 * @return the modified date of this subject
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this subject.
	 *
	 * @param modifiedDate the modified date of this subject
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the subject code of this subject.
	 *
	 * @return the subject code of this subject
	 */
	@AutoEscape
	public String getSubjectCode();

	/**
	 * Sets the subject code of this subject.
	 *
	 * @param subjectCode the subject code of this subject
	 */
	public void setSubjectCode(String subjectCode);

	/**
	 * Returns the subject name of this subject.
	 *
	 * @return the subject name of this subject
	 */
	@AutoEscape
	public String getSubjectName();

	/**
	 * Sets the subject name of this subject.
	 *
	 * @param subjectName the subject name of this subject
	 */
	public void setSubjectName(String subjectName);

	/**
	 * Returns the credit of this subject.
	 *
	 * @return the credit of this subject
	 */
	public int getCredit();

	/**
	 * Sets the credit of this subject.
	 *
	 * @param credit the credit of this subject
	 */
	public void setCredit(int credit);

	/**
	 * Returns the curriculum ID of this subject.
	 *
	 * @return the curriculum ID of this subject
	 */
	public long getCurriculumId();

	/**
	 * Sets the curriculum ID of this subject.
	 *
	 * @param curriculumId the curriculum ID of this subject
	 */
	public void setCurriculumId(long curriculumId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(hu.unideb.inf.model.Subject subject);

	@Override
	public int hashCode();

	@Override
	public CacheModel<hu.unideb.inf.model.Subject> toCacheModel();

	@Override
	public hu.unideb.inf.model.Subject toEscapedModel();

	@Override
	public hu.unideb.inf.model.Subject toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}