/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import hu.unideb.inf.model.Curriculum;
import hu.unideb.inf.model.CurriculumModel;
import hu.unideb.inf.model.CurriculumSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Curriculum service. Represents a row in the &quot;unideb_syllabus_manager_Curriculum&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CurriculumModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CurriculumImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see CurriculumImpl
 * @see Curriculum
 * @see CurriculumModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CurriculumModelImpl extends BaseModelImpl<Curriculum>
	implements CurriculumModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a curriculum model instance should use the {@link Curriculum} interface instead.
	 */
	public static final String TABLE_NAME = "unideb_syllabus_manager_Curriculum";
	public static final Object[][] TABLE_COLUMNS = {
			{ "curriculumId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "curriculumCode", Types.VARCHAR },
			{ "curriculumName", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("curriculumId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("curriculumCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("curriculumName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table unideb_syllabus_manager_Curriculum (curriculumId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,curriculumCode VARCHAR(75) null,curriculumName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table unideb_syllabus_manager_Curriculum";
	public static final String ORDER_BY_JPQL = " ORDER BY curriculum.curriculumCode ASC, curriculum.curriculumName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY unideb_syllabus_manager_Curriculum.curriculumCode ASC, unideb_syllabus_manager_Curriculum.curriculumName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(hu.unideb.inf.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.hu.unideb.inf.model.Curriculum"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(hu.unideb.inf.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.hu.unideb.inf.model.Curriculum"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(hu.unideb.inf.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.hu.unideb.inf.model.Curriculum"),
			true);
	public static final long CURRICULUMCODE_COLUMN_BITMASK = 1L;
	public static final long CURRICULUMNAME_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Curriculum toModel(CurriculumSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Curriculum model = new CurriculumImpl();

		model.setCurriculumId(soapModel.getCurriculumId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCurriculumCode(soapModel.getCurriculumCode());
		model.setCurriculumName(soapModel.getCurriculumName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Curriculum> toModels(CurriculumSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Curriculum> models = new ArrayList<Curriculum>(soapModels.length);

		for (CurriculumSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(hu.unideb.inf.service.util.PropsUtil.get(
				"lock.expiration.time.hu.unideb.inf.model.Curriculum"));

	public CurriculumModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _curriculumId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCurriculumId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _curriculumId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Curriculum.class;
	}

	@Override
	public String getModelClassName() {
		return Curriculum.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("curriculumId", getCurriculumId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("curriculumCode", getCurriculumCode());
		attributes.put("curriculumName", getCurriculumName());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long curriculumId = (Long)attributes.get("curriculumId");

		if (curriculumId != null) {
			setCurriculumId(curriculumId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String curriculumCode = (String)attributes.get("curriculumCode");

		if (curriculumCode != null) {
			setCurriculumCode(curriculumCode);
		}

		String curriculumName = (String)attributes.get("curriculumName");

		if (curriculumName != null) {
			setCurriculumName(curriculumName);
		}
	}

	@JSON
	@Override
	public long getCurriculumId() {
		return _curriculumId;
	}

	@Override
	public void setCurriculumId(long curriculumId) {
		_curriculumId = curriculumId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCurriculumCode() {
		if (_curriculumCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _curriculumCode;
		}
	}

	@Override
	public void setCurriculumCode(String curriculumCode) {
		_columnBitmask = -1L;

		if (_originalCurriculumCode == null) {
			_originalCurriculumCode = _curriculumCode;
		}

		_curriculumCode = curriculumCode;
	}

	public String getOriginalCurriculumCode() {
		return GetterUtil.getString(_originalCurriculumCode);
	}

	@JSON
	@Override
	public String getCurriculumName() {
		if (_curriculumName == null) {
			return StringPool.BLANK;
		}
		else {
			return _curriculumName;
		}
	}

	@Override
	public void setCurriculumName(String curriculumName) {
		_columnBitmask = -1L;

		_curriculumName = curriculumName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Curriculum.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Curriculum toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Curriculum)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CurriculumImpl curriculumImpl = new CurriculumImpl();

		curriculumImpl.setCurriculumId(getCurriculumId());
		curriculumImpl.setGroupId(getGroupId());
		curriculumImpl.setCompanyId(getCompanyId());
		curriculumImpl.setUserId(getUserId());
		curriculumImpl.setUserName(getUserName());
		curriculumImpl.setCreateDate(getCreateDate());
		curriculumImpl.setModifiedDate(getModifiedDate());
		curriculumImpl.setCurriculumCode(getCurriculumCode());
		curriculumImpl.setCurriculumName(getCurriculumName());

		curriculumImpl.resetOriginalValues();

		return curriculumImpl;
	}

	@Override
	public int compareTo(Curriculum curriculum) {
		int value = 0;

		value = getCurriculumCode().compareTo(curriculum.getCurriculumCode());

		if (value != 0) {
			return value;
		}

		value = getCurriculumName().compareTo(curriculum.getCurriculumName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Curriculum)) {
			return false;
		}

		Curriculum curriculum = (Curriculum)obj;

		long primaryKey = curriculum.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CurriculumModelImpl curriculumModelImpl = this;

		curriculumModelImpl._setModifiedDate = false;

		curriculumModelImpl._originalCurriculumCode = curriculumModelImpl._curriculumCode;

		curriculumModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Curriculum> toCacheModel() {
		CurriculumCacheModel curriculumCacheModel = new CurriculumCacheModel();

		curriculumCacheModel.curriculumId = getCurriculumId();

		curriculumCacheModel.groupId = getGroupId();

		curriculumCacheModel.companyId = getCompanyId();

		curriculumCacheModel.userId = getUserId();

		curriculumCacheModel.userName = getUserName();

		String userName = curriculumCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			curriculumCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			curriculumCacheModel.createDate = createDate.getTime();
		}
		else {
			curriculumCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			curriculumCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			curriculumCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		curriculumCacheModel.curriculumCode = getCurriculumCode();

		String curriculumCode = curriculumCacheModel.curriculumCode;

		if ((curriculumCode != null) && (curriculumCode.length() == 0)) {
			curriculumCacheModel.curriculumCode = null;
		}

		curriculumCacheModel.curriculumName = getCurriculumName();

		String curriculumName = curriculumCacheModel.curriculumName;

		if ((curriculumName != null) && (curriculumName.length() == 0)) {
			curriculumCacheModel.curriculumName = null;
		}

		return curriculumCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{curriculumId=");
		sb.append(getCurriculumId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", curriculumCode=");
		sb.append(getCurriculumCode());
		sb.append(", curriculumName=");
		sb.append(getCurriculumName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("hu.unideb.inf.model.Curriculum");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>curriculumId</column-name><column-value><![CDATA[");
		sb.append(getCurriculumId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>curriculumCode</column-name><column-value><![CDATA[");
		sb.append(getCurriculumCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>curriculumName</column-name><column-value><![CDATA[");
		sb.append(getCurriculumName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Curriculum.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Curriculum.class
		};
	private long _curriculumId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _curriculumCode;
	private String _originalCurriculumCode;
	private String _curriculumName;
	private long _columnBitmask;
	private Curriculum _escapedModel;
}