/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hu.unideb.inf.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import hu.unideb.inf.model.Subject;
import hu.unideb.inf.model.SubjectModel;
import hu.unideb.inf.model.SubjectSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Subject service. Represents a row in the &quot;unideb_syllabus_manager_Subject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SubjectModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubjectImpl}.
 * </p>
 *
 * @author Adam Kiss
 * @see SubjectImpl
 * @see Subject
 * @see SubjectModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SubjectModelImpl extends BaseModelImpl<Subject>
	implements SubjectModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subject model instance should use the {@link Subject} interface instead.
	 */
	public static final String TABLE_NAME = "unideb_syllabus_manager_Subject";
	public static final Object[][] TABLE_COLUMNS = {
			{ "subjectId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "subjectCode", Types.VARCHAR },
			{ "subjectName", Types.VARCHAR },
			{ "credit", Types.INTEGER },
			{ "curriculumId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("subjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("subjectCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subjectName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("credit", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("curriculumId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table unideb_syllabus_manager_Subject (subjectId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,subjectCode TEXT null,subjectName TEXT null,credit INTEGER,curriculumId LONG)";
	public static final String TABLE_SQL_DROP = "drop table unideb_syllabus_manager_Subject";
	public static final String ORDER_BY_JPQL = " ORDER BY subject.subjectCode ASC, subject.subjectName ASC, subject.credit ASC";
	public static final String ORDER_BY_SQL = " ORDER BY unideb_syllabus_manager_Subject.subjectCode ASC, unideb_syllabus_manager_Subject.subjectName ASC, unideb_syllabus_manager_Subject.credit ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(hu.unideb.inf.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.hu.unideb.inf.model.Subject"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(hu.unideb.inf.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.hu.unideb.inf.model.Subject"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(hu.unideb.inf.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.hu.unideb.inf.model.Subject"),
			true);
	public static final long CURRICULUMID_COLUMN_BITMASK = 1L;
	public static final long SUBJECTCODE_COLUMN_BITMASK = 2L;
	public static final long SUBJECTNAME_COLUMN_BITMASK = 4L;
	public static final long CREDIT_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Subject toModel(SubjectSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Subject model = new SubjectImpl();

		model.setSubjectId(soapModel.getSubjectId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setSubjectCode(soapModel.getSubjectCode());
		model.setSubjectName(soapModel.getSubjectName());
		model.setCredit(soapModel.getCredit());
		model.setCurriculumId(soapModel.getCurriculumId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Subject> toModels(SubjectSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Subject> models = new ArrayList<Subject>(soapModels.length);

		for (SubjectSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(hu.unideb.inf.service.util.PropsUtil.get(
				"lock.expiration.time.hu.unideb.inf.model.Subject"));

	public SubjectModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subjectId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubjectId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subjectId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Subject.class;
	}

	@Override
	public String getModelClassName() {
		return Subject.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("subjectId", getSubjectId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("subjectCode", getSubjectCode());
		attributes.put("subjectName", getSubjectName());
		attributes.put("credit", getCredit());
		attributes.put("curriculumId", getCurriculumId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long subjectId = (Long)attributes.get("subjectId");

		if (subjectId != null) {
			setSubjectId(subjectId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String subjectCode = (String)attributes.get("subjectCode");

		if (subjectCode != null) {
			setSubjectCode(subjectCode);
		}

		String subjectName = (String)attributes.get("subjectName");

		if (subjectName != null) {
			setSubjectName(subjectName);
		}

		Integer credit = (Integer)attributes.get("credit");

		if (credit != null) {
			setCredit(credit);
		}

		Long curriculumId = (Long)attributes.get("curriculumId");

		if (curriculumId != null) {
			setCurriculumId(curriculumId);
		}
	}

	@JSON
	@Override
	public long getSubjectId() {
		return _subjectId;
	}

	@Override
	public void setSubjectId(long subjectId) {
		_subjectId = subjectId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getSubjectCode() {
		if (_subjectCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _subjectCode;
		}
	}

	@Override
	public void setSubjectCode(String subjectCode) {
		_columnBitmask = -1L;

		if (_originalSubjectCode == null) {
			_originalSubjectCode = _subjectCode;
		}

		_subjectCode = subjectCode;
	}

	public String getOriginalSubjectCode() {
		return GetterUtil.getString(_originalSubjectCode);
	}

	@JSON
	@Override
	public String getSubjectName() {
		if (_subjectName == null) {
			return StringPool.BLANK;
		}
		else {
			return _subjectName;
		}
	}

	@Override
	public void setSubjectName(String subjectName) {
		_columnBitmask = -1L;

		_subjectName = subjectName;
	}

	@JSON
	@Override
	public int getCredit() {
		return _credit;
	}

	@Override
	public void setCredit(int credit) {
		_columnBitmask = -1L;

		_credit = credit;
	}

	@JSON
	@Override
	public long getCurriculumId() {
		return _curriculumId;
	}

	@Override
	public void setCurriculumId(long curriculumId) {
		_columnBitmask |= CURRICULUMID_COLUMN_BITMASK;

		if (!_setOriginalCurriculumId) {
			_setOriginalCurriculumId = true;

			_originalCurriculumId = _curriculumId;
		}

		_curriculumId = curriculumId;
	}

	public long getOriginalCurriculumId() {
		return _originalCurriculumId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Subject.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Subject toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Subject)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubjectImpl subjectImpl = new SubjectImpl();

		subjectImpl.setSubjectId(getSubjectId());
		subjectImpl.setGroupId(getGroupId());
		subjectImpl.setCompanyId(getCompanyId());
		subjectImpl.setUserId(getUserId());
		subjectImpl.setUserName(getUserName());
		subjectImpl.setCreateDate(getCreateDate());
		subjectImpl.setModifiedDate(getModifiedDate());
		subjectImpl.setSubjectCode(getSubjectCode());
		subjectImpl.setSubjectName(getSubjectName());
		subjectImpl.setCredit(getCredit());
		subjectImpl.setCurriculumId(getCurriculumId());

		subjectImpl.resetOriginalValues();

		return subjectImpl;
	}

	@Override
	public int compareTo(Subject subject) {
		int value = 0;

		value = getSubjectCode().compareTo(subject.getSubjectCode());

		if (value != 0) {
			return value;
		}

		value = getSubjectName().compareTo(subject.getSubjectName());

		if (value != 0) {
			return value;
		}

		if (getCredit() < subject.getCredit()) {
			value = -1;
		}
		else if (getCredit() > subject.getCredit()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Subject)) {
			return false;
		}

		Subject subject = (Subject)obj;

		long primaryKey = subject.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SubjectModelImpl subjectModelImpl = this;

		subjectModelImpl._setModifiedDate = false;

		subjectModelImpl._originalSubjectCode = subjectModelImpl._subjectCode;

		subjectModelImpl._originalCurriculumId = subjectModelImpl._curriculumId;

		subjectModelImpl._setOriginalCurriculumId = false;

		subjectModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Subject> toCacheModel() {
		SubjectCacheModel subjectCacheModel = new SubjectCacheModel();

		subjectCacheModel.subjectId = getSubjectId();

		subjectCacheModel.groupId = getGroupId();

		subjectCacheModel.companyId = getCompanyId();

		subjectCacheModel.userId = getUserId();

		subjectCacheModel.userName = getUserName();

		String userName = subjectCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			subjectCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			subjectCacheModel.createDate = createDate.getTime();
		}
		else {
			subjectCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subjectCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			subjectCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		subjectCacheModel.subjectCode = getSubjectCode();

		String subjectCode = subjectCacheModel.subjectCode;

		if ((subjectCode != null) && (subjectCode.length() == 0)) {
			subjectCacheModel.subjectCode = null;
		}

		subjectCacheModel.subjectName = getSubjectName();

		String subjectName = subjectCacheModel.subjectName;

		if ((subjectName != null) && (subjectName.length() == 0)) {
			subjectCacheModel.subjectName = null;
		}

		subjectCacheModel.credit = getCredit();

		subjectCacheModel.curriculumId = getCurriculumId();

		return subjectCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{subjectId=");
		sb.append(getSubjectId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", subjectCode=");
		sb.append(getSubjectCode());
		sb.append(", subjectName=");
		sb.append(getSubjectName());
		sb.append(", credit=");
		sb.append(getCredit());
		sb.append(", curriculumId=");
		sb.append(getCurriculumId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("hu.unideb.inf.model.Subject");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>subjectId</column-name><column-value><![CDATA[");
		sb.append(getSubjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subjectCode</column-name><column-value><![CDATA[");
		sb.append(getSubjectCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subjectName</column-name><column-value><![CDATA[");
		sb.append(getSubjectName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>credit</column-name><column-value><![CDATA[");
		sb.append(getCredit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>curriculumId</column-name><column-value><![CDATA[");
		sb.append(getCurriculumId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Subject.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Subject.class
		};
	private long _subjectId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _subjectCode;
	private String _originalSubjectCode;
	private String _subjectName;
	private int _credit;
	private long _curriculumId;
	private long _originalCurriculumId;
	private boolean _setOriginalCurriculumId;
	private long _columnBitmask;
	private Subject _escapedModel;
}